name: Build

on:
  push:
jobs:
  build-project:
    name: Build Project
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
      - name: Debug Qt Installation
        run: |
          qmake --version
      - name: Build Project
        env:
          CMAKE_PREFIX_PATH: ${{env.Qt6_Dir}}
        uses: threeal/cmake-action@v2.1.0
